url: growonlinetoday.com
baseurl:

# Site settings
title: Grow Online Today
email: sanjit@growonlinetoday.com
description: "Helping Businesses grow their profits"

# Team names, titles and social links
people:
  - name: Sanjit Chakrabarti
    pic: Sanjit
    position: Founder
    social:
      - title: facebook
        url: https://facebook.com/sujitsanjit
      - title: linkedin
        url: https://linkedin.com/in/sanjit-chakrabarti-pro/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://facebook.com/growonlinetoday
  - title: linkedin
    url: https://linkedin.com/in/sanjit-chakrabarti-pro/

# Postal address (add as many lines as necessary)
address:
  - line: National Park, Naihati
  - line: North 24 Parganas, West Bengal

# Build settings
markdown: kramdown
permalink: pretty
